### ISSUE TITLE
Multiline

### ISSUE THREAD

**Issue by Aiysen** [Mwni/pixi-text-input#4]
Hello.

Is option to make multiline input form?

**Comment by Mwni** [comment]
No, not at the moment. It would be required to swap out the input with a textarea. And textareas have their own set of complexities (scrolling, resizing, line height, word wrapping).

If there's enough demand for it Ill do it.

For now you can try to change the sourcecode to instantiate a textarea instead of an input. (function `_createDOMInput()` on line 119.

**Comment by Aiysen** [comment]
I think multiline text form does not need scroll, for me.
PIXI.TextStyle already supports line height and word wrapping

**Comment by Mwni** [comment]
Yes it does support it, however it will probably render differently on pixi. Same goes for line height.
Nevertheless, there's some research to be done...

**Comment by Aiysen** [comment]
Could you add multiline in any simple mode?

**Comment by Mwni** [comment]
Try the new version with the option:
```
new PIXI.TextInput({
	input: {
		multiline: true,
		fontFamily: 'Arial',
		fontSize: '36px',
		...
	},
	box: ...
})
```
Might want to turn off textSubstitution, as there is a positional jump when focusing the input, due to the discrepancy of the html input text rendering and the canvas text rendering. There's unfortunately no way of determining the native font height.

**Comment by Aiysen** [comment]
I think, its okay for now.
Big thank you!
